# Generated by Django 3.2.23 on 2024-08-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='categoria',
            field=models.ManyToManyField(related_name='relevancia_checks', to='check.Categoria'),
        ),
    ]
