# Generated by Django 3.2.23 on 2024-08-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_check_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='check',
            name='categoria',
            field=models.ManyToManyField(related_name='relevancia_check', to='check.Categoria'),
        ),
    ]
