# Generated by Django 3.2.23 on 2024-08-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_auto_20240815_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='numero_cotizacion',
            field=models.IntegerField(null=True),
        ),
    ]
