# Generated by Django 3.2.23 on 2024-08-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_check_numero_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='estatus',
            field=models.ManyToManyField(related_name='status', to='check.Status'),
        ),
    ]
