# Generated by Django 5.1 on 2024-08-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0008_check_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='motivo_rechazo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
