# Generated by Django 5.1 on 2024-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_check_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, null=True)),
                ('empresa_cliente', models.CharField(max_length=100, null=True)),
                ('direccion_cliente', models.CharField(max_length=100, null=True)),
                ('telefono_cliente', models.IntegerField(null=True)),
                ('email_cliente', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='check',
            name='nombre_empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='cliente',
            field=models.ManyToManyField(related_name='cliente', to='check.cliente'),
        ),
    ]
