# Generated by Django 5.1 on 2024-08-29 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_cliente_remove_check_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_rechazo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='check',
            name='motivo_rechazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_reason', to='check.reject'),
        ),
    ]
