# Generated by Django 5.1 on 2024-08-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0011_reject_alter_check_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='motivo_rechazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_reason', to='check.reject'),
        ),
    ]
