# Generated by Django 5.1 on 2024-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0012_alter_check_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='motivo_rechazo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Reject',
        ),
    ]
