# Generated by Django 5.1 on 2024-08-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0014_alter_check_frecuencia_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
