# Generated by Django 5.1 on 2024-09-02 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0016_alter_check_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 17, 27, 44, 334136, tzinfo=datetime.timezone.utc)),
        ),
    ]
