# Generated by Django 5.1 on 2024-09-02 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0019_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 18, 34, 29, 83064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
