# Generated by Django 5.1 on 2024-09-02 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0020_alter_check_fecha_expiracion_alter_vigencia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 18, 36, 11, 875246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Vigencia',
        ),
    ]
