# Generated by Django 5.1 on 2024-09-02 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0022_alter_check_fecha_expiracion_alter_check_vigente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='vigente',
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 18, 43, 14, 807686, tzinfo=datetime.timezone.utc)),
        ),
    ]
