# Generated by Django 5.1 on 2024-09-02 18:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0023_remove_check_vigente_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 18, 58, 44, 160513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='check',
            name='vigente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='check.vigencia'),
            preserve_default=False,
        ),
    ]
