# Generated by Django 5.1 on 2024-09-02 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0024_vigencia_alter_check_fecha_expiracion_check_vigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 19, 18, 15, 306357, tzinfo=datetime.timezone.utc)),
        ),
    ]
