# Generated by Django 5.1 on 2024-09-02 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0026_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='vigente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 19, 27, 59, 95572, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Vigencia',
        ),
    ]
