# Generated by Django 5.1 on 2024-09-04 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0036_alter_check_cliente_alter_check_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 18, 16, 23, 496196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='nombre_proyecto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='numero_tintas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='tecnologia_fabricacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
