# Generated by Django 5.1 on 2024-09-04 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0037_alter_check_fecha_expiracion_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='check',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='relevancia_check', to='check.categoria'),
        ),
        migrations.AlterField(
            model_name='check',
            name='cliente',
            field=models.ManyToManyField(blank=True, related_name='cliente', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 19, 58, 47, 574384, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='precio_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
