# Generated by Django 5.1 on 2024-09-05 18:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0038_delete_cliente_alter_check_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='check',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 18, 7, 14, 372107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='check',
            name='cliente',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
