# Generated by Django 5.1 on 2024-09-05 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0040_remove_check_cliente_alter_check_fecha_expiracion_and_more'),
    ]

    operations = [
      
       
        migrations.AddField(
            model_name='check',
            name='cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
