# Generated by Django 5.1 on 2024-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=255)),
                ('encargado_cuenta', models.CharField(max_length=255)),
                ('etapa', models.CharField(choices=[('inicial', 'Inicial'), ('primer_contacto', 'Primer Contacto'), ('seguimiento', 'Seguimiento'), ('propuesta_enviada', 'Propuesta Enviada'), ('cerrado', 'Cerrado'), ('perdido', 'Perdido')], default='inicial', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('sitio_web', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
