# Generated by Django 5.1 on 2024-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, null=True)),
                ('empresa_cliente', models.CharField(max_length=100, null=True)),
                ('direccion_cliente', models.CharField(max_length=100, null=True)),
                ('telefono_cliente', models.IntegerField(null=True)),
                ('email_cliente', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
