# Generated by Django 5.1 on 2024-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
