# Generated by Django 5.1 on 2024-10-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='posicion',
            field=models.CharField(default='Desconocido', max_length=255, null=True),
        ),
    ]
