# Generated by Django 5.1 on 2024-09-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='propietario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
