# Generated by Django 5.1 on 2024-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_pipeline',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Primer-contacto', 'Primer-contacto'), ('Pendiente-de-respuesta', 'Pendiente-de-respuesta'), ('Recordatorio-enviado', 'Recordatorio-enviado'), ('Reunion-programada', 'Reunion-programada'), ('Interesado', 'Interesado'), ('Propuesta-en-revision', 'Propuesta-en-revision'), ('Negociacion-activa', 'Negociacion-activa'), ('interaccion-perdida', 'interaccion-perdida'), ('Venta-cerrada', 'Venta-cerrada'), ('Cliente-inactivo', 'Cliente-inactivo'), ('Venta-perdida', 'Venta-perdida'), ('Renovacion-o-actualicion', 'Renovacion-o-actualicion')], default='Nuevo', max_length=24),
        ),
    ]
