# Generated by Django 5.1 on 2024-09-05 19:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gerente', models.CharField(max_length=100, null=True)),
                ('numero_cotizacion', models.IntegerField(null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('volumen_estimado', models.IntegerField(blank=True, null=True)),
                ('numero_tintas', models.IntegerField(blank=True, null=True)),
                ('tecnologia_fabricacion', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('producto_nuevo', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('precio_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios_adicionales', models.TextField(blank=True, null=True)),
                ('frecuencia_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=100)),
                ('fecha_expiracion', models.DateTimeField(default=datetime.datetime(2024, 9, 5, 19, 30, 24, 834736, tzinfo=datetime.timezone.utc))),
                ('vigente', models.BooleanField(default=True, null=True)),
                ('cliente', models.CharField(max_length=100, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ManyToManyField(blank=True, related_name='relevancia_check', to='cotizaciones.categoria')),
                ('estatus', models.ManyToManyField(blank=True, related_name='status', to='cotizaciones.status')),
            ],
        ),
    ]
