# Generated by Django 5.1 on 2024-09-05 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 19, 31, 37, 140755, tzinfo=datetime.timezone.utc)),
        ),
    ]
