# Generated by Django 5.1 on 2024-09-06 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_check_estado_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 8, 0, 2, 627388, tzinfo=datetime.timezone.utc)),
        ),
    ]
