# Generated by Django 5.1 on 2024-09-06 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 19, 8, 44, 143171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='numero_cotizacion',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='precio_objetivo',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
