# Generated by Django 5.1 on 2024-09-06 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 21, 47, 29, 693548, tzinfo=datetime.timezone.utc)),
        ),
    ]
