# Generated by Django 5.1 on 2024-09-09 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 23, 41, 59, 300877, tzinfo=datetime.timezone.utc)),
        ),
    ]
