# Generated by Django 5.1 on 2024-09-12 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_alter_check_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 20, 3, 42, 50808, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_solicitud',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 12, 20, 3, 43, 49808, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
