# Generated by Django 5.1 on 2024-09-12 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_alter_check_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 20, 5, 37, 199199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 20, 5, 38, 199199, tzinfo=datetime.timezone.utc)),
        ),
    ]
