# Generated by Django 5.1 on 2024-09-19 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0021_remove_comentarios_check_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 20, 4, 34, 843267, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_solicitud',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 14, 4, 34, 843267)),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 14, 4, 34, 844267)),
        ),
    ]
