# Generated by Django 5.1 on 2024-10-05 20:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_delete_empresa_cliente_posicion'),
        ('cotizaciones', '0036_alter_check_fecha_expiracion_and_more'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='check',
            name='frecuencia_compra',
        ),
        migrations.RemoveField(
            model_name='check',
            name='lugar_entrega',
        ),
        migrations.RemoveField(
            model_name='check',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='check',
            name='nombre_gerente',
        ),
        migrations.RemoveField(
            model_name='check',
            name='numero_tintas',
        ),
        migrations.RemoveField(
            model_name='check',
            name='precio_objetivo',
        ),
        migrations.RemoveField(
            model_name='check',
            name='producto_nuevo',
        ),
        migrations.RemoveField(
            model_name='check',
            name='tecnologia_fabricacion',
        ),
        migrations.RemoveField(
            model_name='check',
            name='tipo_producto',
        ),
        migrations.RemoveField(
            model_name='check',
            name='volumen_estimado',
        ),
        migrations.AlterField(
            model_name='check',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 20, 7, 34, 442189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='fecha_solicitud',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 14, 7, 34, 442189)),
        ),
        migrations.RemoveField(
            model_name='check',
            name='nombre_empresa',
        ),
        migrations.AlterField(
            model_name='check',
            name='numero_cotizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 14, 7, 34, 443188)),
        ),
        migrations.AddField(
            model_name='check',
            name='nombre_empresa',
            field=models.ManyToManyField(to='empresas.empresa'),
        ),
    ]
