# Generated by Django 5.1 on 2024-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('x_twitter', models.URLField(blank=True, null=True, verbose_name='X (Twitter)')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('video_corporativo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
