# Generated by Django 5.1 on 2024-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
