# Generated by Django 5.1 on 2024-09-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0002_alter_vendedores_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='propietario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
