# Generated by Django 5.1 on 2024-09-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0003_vendedores_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedores',
            name='propietario',
        ),
    ]
